from fastapi import FastAPI , HTTPException
from pydantic import BaseModel , Field
from src.graph import agent
import traceback

app=FastAPI(title="Research Assistant" , description="A Multi Agent Research Assitant" ,  version="1.0.0")

class UserRequest(BaseModel) :
    user_query : str = Field(... , description="The user query requested by the user to generate a report for.")

class UserPost(BaseModel) :
    written_report : str = Field(... , description="The final research report generated by the agent returned for user view.")

@app.post("/request")
def request_endpoint(request : UserRequest) :
    user_query = request.user_query

    initial_state = {
        "user_query" : user_query
    }

    try :
        final_state = agent.invoke(initial_state)
        report = final_state.get("written_report" , "No Report Generated ! ")

        return UserPost(
            written_report = report
        )

    except Exception as e :
        print("\n--- 🚨 GRAPH EXECUTION FAILED ---")
        traceback.print_exc()
        print("---------------------------------\n")
        raise HTTPException(status_code=500, detail=str(e))